src/routes/configuracion.py
# Importaciones
from flask import Blueprint, session, render_template, request, flash, redirect, url_for
from ..utils.guardar_contrasena import verify_pass, change_pass, secure_pass

# Se crea la ruta configuracion
configuracion_bp = Blueprint('configuracion', __name__)

@configuracion_bp.route('/configuracion')
def configuracion():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']

        return render_template('pages/configuracion.html', empleado = empleado, roles = roles, personal = personal)

# Se crea la ruta para guardar la contraseña
save_pass_bp = Blueprint('save_pass', __name__)
@save_pass_bp.route('/save_pass', methods=['POST'])
def save_pass():
    if 'user' in session:
        empleado = session['empleado']
        old_pass = request.form['oldPass']
        new_pass = request.form['newPass']
        confirm_pass = request.form['confirmPass']

        # Se verifica la contraseña
        if verify_pass(empleado, old_pass):
            # La contraseña nueva tiene que coincidir en los dos campos que se ingreso
            if new_pass == confirm_pass:
                # Verificación de si la contraseña cumple la seguridad establecida
                if secure_pass(new_pass):
                    # Si se cambio la contraseña y cumple se guarda
                    if change_pass(empleado, new_pass):
                        flash('Se guardó con éxito', 'success')
                        return redirect(url_for('configuracion.configuracion'))
                    else:
                        return "Error al cambiar la contraseña"
                else:
                    return "La nueva contraseña no cumple con los requisitos de seguridad"                
            else:
                return "Las contraseñas no coinciden"
        else:
            return "La contraseña actual es incorrecta"
        
    else:
        return redirect(url_for('index'))

src/routes/descargas.py
# Importaciones
from flask import Blueprint, session, render_template, request, send_file
from src.utils.descargas import descargar_nomina, descargar_nomina_bajas, descargar_inventario_recursos, obtener_dias_empleado, generar_excel
from openpyxl import Workbook
from io import BytesIO
# Se crea la ruta resources
descargas_bp = Blueprint('descargas', __name__)

@descargas_bp.route('/descargas')
def descargas():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']
        print(personal)
        return render_template('pages/descargas.html', empleado = empleado, roles = roles, personal = personal)

descargar_bp = Blueprint('descargar', __name__)
@descargar_bp.route('/descargar')    
def descargar():
    # Obtener el parámetro 'accion' de la URL
    accion = request.args.get('accion')
    personal = session['personal']
    area = session['area']
    # Determinar qué acción realizar según el valor del parámetro 'accion'
    if accion == 'nomina':
        return descargar_nomina(personal)
    elif accion == 'nomina_bajas':
        return descargar_nomina_bajas(area)
    elif accion == 'inventario_recursos':
        return descargar_inventario_recursos()
    else:
        # Acción no válida, redirigir a alguna página de error o manejarla de otra manera
        return 'Acción no válida'
    
descargar_nov_mens_bp = Blueprint('descargar_nov_mens', __name__)
@descargar_nov_mens_bp.route('/descargar_nov_mens', methods=['GET', 'POST'])    
def descargar_nov_mens():
    personal = session.get('personal', [])
    mes = int(request.form.get('mes'))
    print(personal)
    novedades = []

    for empleado in personal:
        novedades.append(obtener_dias_empleado(empleado, mes))

    output = generar_excel_novs(novedades)

    # Devolver el archivo Excel como respuesta
    return send_file(
        output,
        as_attachment=True,
        download_name="novedades_mensuales.xlsx",
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

def generar_excel_novs(novedades):
    # Crear un nuevo libro de trabajo
    wb = Workbook()
    # Seleccionar la primera hoja del libro de trabajo
    ws = wb.active
    # Establecer los encabezados de las columnas
    ws.append(['Empleado', 'Fecha Inicio', 'Fecha Final', 'Estado', 'Concepto', ' Causa', 'Fecha solicitud', 'Fecha cambio de estado', 'Superior', 'Area'])
    
    for lista_novedades in novedades:
        for novedad in lista_novedades:
            concepto = novedad.get('concepto', '')
            empleado = novedad.get('empleado', '')
            if concepto in ['dia_ausencia', 'dia_vacaciones']:
                fecha_inicio = novedad.get('fecha_inicio', '')
                fecha_final = novedad.get('fecha_final', '')
                estado = novedad.get('estado', '')
            elif concepto in ['dia_home', 'dia_estudio']:
                fecha_inicio = novedad.get('fecha_inicio', '')
                fecha_final = ''
                estado = novedad.get('estado', '')
            fecha_solicitud = novedad.get('fecha_solicitud', '')
            fecha_cambio_estado = novedad.get('fecha_cambio_estado', '')
            superior = novedad.get('superior', '')
            area = novedad.get('area', '')
            causa = novedad.get('causa', '')
            if concepto == 'dia_ausencia':
                concepto = 'Ausencia'
            elif concepto == 'dia_vacaciones':
                concepto = 'Vacaciones'
            elif concepto == 'dia_home':
                concepto = 'Home Office'
            elif concepto == 'dia_estudio':
                concepto = 'Estudio'

            # Agregar una fila con los datos de la novedad actual
            ws.append([empleado, fecha_inicio, fecha_final, estado, concepto, causa, fecha_solicitud, fecha_cambio_estado, superior, area])

    # Crear un objeto de bytes en memoria para almacenar el archivo Excel
    output = BytesIO()
    # Guardar el libro de trabajo en el objeto de bytes
    wb.save(output)
    # Reiniciar el cursor del objeto de bytes al inicio para permitir su lectura
    output.seek(0)

    return output

src/routes/documentos.py
from flask import Blueprint, session, render_template, request, flash, redirect, url_for

documentos_bp = Blueprint('documentos', __name__)
@documentos_bp.route('/documentos')
def documentos():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']
        lista_documentos = [
            {"nombre": "Assisto Paraguay - CCGG", "enlace": "https://drive.google.com/drive/folders/1IOMGhMxwCk4HoPfHlT1HcKomMinD_R9b"},
            {"nombre": "Assist 365 - Login", "enlace": "https://docs.google.com/document/d/1YrkLYWA5CdY9KjGcko6mPbJdEDWWRXhzY83KZJGaviU/edit"},
            
            # Agrega más documentos aquí si es necesario
        ]


        return render_template('pages/documentos.html', empleado = empleado, roles = roles, personal = personal, lista_documentos=lista_documentos)

src/routes/files.py
from flask import Blueprint, send_from_directory, render_template, url_for
import os

# Crea el blueprint
files_bp = Blueprint('files_bp', __name__, template_folder='templates')

# Configura la ruta donde se almacenan los archivos
current_dir = os.path.dirname(os.path.abspath(__file__))
FILE_DIRECTORY = os.path.join(current_dir, '../../static/files')

def list_items(directory):
    items = []
    for name in os.listdir(directory):
        path = os.path.join(directory, name)
        if os.path.isdir(path):
            items.append({'type': 'folder', 'name': name})
        else:
            items.append({'type': 'file', 'name': name})
    return items

@files_bp.route('/')
@files_bp.route('/<path:subdir>')
def files(subdir=''):
    directory = os.path.join(FILE_DIRECTORY, subdir)
    items = list_items(directory)
    return render_template('pages/files.html', items=items, subdir=subdir)

@files_bp.route('/download/<path:filename>')
def download_file(filename):
    return send_from_directory(FILE_DIRECTORY, filename)

src/routes/inicio.py
# Importaciones
from flask import Blueprint, render_template, session
from ..utils.tablas_inicio import obtener_cumpleanios, obtener_claves
from ..utils.date_db import bring_approved, obtener_feriados
import json

# Crea un objeto Blueprint
inicio_bp = Blueprint('inicio', __name__)

# Define la ruta para la página de inicio de sesión
@inicio_bp.route('/inicio')
def inicio():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        area = session['area']
        jerarquia = session['jerarquia']
        personal = session['personal']
        print(roles)
        cumpleanios = obtener_cumpleanios()
        claves = obtener_claves(area)
        fechas_aprobadas_totales = {}
        # Verificar si personal es una lista
        if isinstance(personal, list):
            for persona in personal:
                fechas_aprobadas = bring_approved(persona)
                fechas_aprobadas_totales[persona] = fechas_aprobadas
        else:
            fechas_aprobadas = bring_approved(personal)
            fechas_aprobadas_totales[personal] = fechas_aprobadas

        fechas_aprobadas_json = json.dumps(fechas_aprobadas_totales)
        #print(fechas_aprobadas_json)
        feriados = obtener_feriados()
        print(feriados)

        return render_template('pages/inicio.html', empleado=empleado, roles=roles, cumpleanios=cumpleanios, area=area, claves=claves, fechas_aprobadas=fechas_aprobadas_json, jerarquia=jerarquia)

src/routes/recursos.py
# Importaciones
from flask import Blueprint, session, render_template
from ..utils.recursos import obtener_recursos_empleado

# Se crea la ruta resources
recursos_bp = Blueprint('recursos', __name__)
@recursos_bp.route('/recursos')
def recursos():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']
        recurso_asignado = obtener_recursos_empleado(empleado)
        
        return render_template('pages/recursos.html', empleado = empleado, roles = roles, personal = personal, recurso_asignado=recurso_asignado)

src/routes/rrhh.py
# Importaciones
from flask import Blueprint, session, render_template
# Se crea la ruta resources
rrhh_bp = Blueprint('rrhh', __name__)
@rrhh_bp.route('/rrhh')
def rrhh():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']
        
        return render_template('pages/rrhh.html', empleado = empleado, roles = roles, personal = personal)

src/routes/sistemas.py
from flask import Blueprint, session, render_template, request, redirect, url_for
from ..utils.sistemas import guardar_reporte_a_sistemas, obtener_reportes_a_sistemas, actualizar_ticket, obtener_empleados_sistemas, obtener_tickets_sistemas
from ..utils.outlook import enviar_correo
# Se crea la ruta resources
sistemas_bp = Blueprint('sistemas', __name__)

@sistemas_bp.route('/sistemas')
def sistemas():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']
        area = session['area']
        reportes_a_sistemas = obtener_reportes_a_sistemas()
        empleados_sistemas = obtener_empleados_sistemas()
        obtener_tickets = obtener_tickets_sistemas(empleado)
        
        return render_template('pages/sistemas.html', empleado = empleado, roles = roles, personal = personal, area=area, reportes_a_sistemas=reportes_a_sistemas, empleados_sistemas=empleados_sistemas, obtener_tickets=obtener_tickets)
    
reportar_a_sistemas_bp = Blueprint('reportar_a_sistemas', __name__)
@reportar_a_sistemas_bp.route('/reportar_a_sistemas', methods=['GET', 'POST'])
def reportar_a_sistemas():
    if 'user' in session:
        empleado = session['empleado']
        if request.method == 'POST':
            categoria = request.form.get('categoria')
            subcategoria = request.form.get('subcategoria')
            tipo_problema = request.form.get('tipo_problema')
            descripcion_problema = request.form.get('descripcion_problema')
            id_equipo = request.form.get('id_equipo')

            guardar_reporte_a_sistemas(categoria, subcategoria, tipo_problema, descripcion_problema, id_equipo, empleado)

            # Llamar a la función para enviar el correo electrónico
            enviar_correo(categoria, subcategoria, tipo_problema, descripcion_problema, id_equipo, empleado)

            return redirect(url_for('sistemas.sistemas'))
        
        return redirect(url_for('sistemas.sistemas'))
    else:
        return redirect(url_for('login'))

modificar_ticket_bp = Blueprint('modificar_ticket', __name__)
@modificar_ticket_bp.route('/modificar_ticket/<int:id>', methods=['POST'])
def modificar_ticket(id):
    if request.method == 'POST':
        estado = request.form.get('estado')
        prioridad = request.form.get('prioridad')
        reportado_a = request.form.get('reportado_a')

        if estado == 'Cerrado':
            actualizar_ticket(id, estado, prioridad, reportado_a, cerrado='Si')
        else:
            actualizar_ticket(id, estado, prioridad, reportado_a, cerrado=False)

        return redirect(url_for('sistemas.sistemas'))
    else:
        pass

empleado_notificado_bp = Blueprint('empleado_notificado', __name__)
@empleado_notificado_bp.route('/empleado_notificado', methods=['POST'])
def empleado_notificado():
    if request.method == 'POST':
        id = request.form.get('id')
        estado = request.form.get('estado')
        prioridad = request.form.get('prioridad')
        reportado_a = request.form.get('reportado_a')

        actualizar_ticket(id, estado, prioridad, reportado_a, cerrado='Fin')
        return redirect(url_for('sistemas.sistemas'))
    else:
        pass

templates/pages/aprobacion.html
{% extends 'components/base.html' %}
{% set roles_editores = ['jefe de area', 'responsable de area', 'supervisor', 'ceo', 'rrhh'] %}

{% block title %}Edición{% endblock %}

{% block content %}
  {% if 'rrhh' not in roles %}
  {% include 'components/aprobacion.html'%}
  {% endif %}
  {% if jerarquia in ['2', '3', '4', '5'] %}
  {% include 'components/dias_aprobados.html'%}
  {% endif %}
  {% if dias_filtrados %}
    {% include 'components/dias_filtrados.html'%}
  {% endif %}
{% endblock %}

templates/pages/ausencia.html
{% extends 'components/base.html' %}


{% block title %}Día de ausencia{% endblock %}

{% block content %}
    <h2>Módulo de días de ausencia</h2>
    <!-- Formulario para guardar día de ausencia -->
    <form action="/save_date" method="POST" class="formDia" onsubmit="return validateDates()">
        <div class="form-group">
            <label for="startDate">Fecha inicial:</label>
            <input type="date" id="startDate" name="startDate" required>
        </div>
        <div class="form-group">
            <label for="endDate">Fecha final:</label>
            <input type="date" id="endDate" name="endDate">
        </div>
        <div class="form-group">
            <label for="typeAbsent">Motivo de Ausencia:</label>
            <select id="typeAbsent" name="typeAbsent" required>
                <option value="Mudanza">Mudanza</option>
                <option value="Accidente">Accidente</option>
                <option value="Enfermedad">Enfermedad</option>
                <option value="Otro">Otro</option>
            </select>
        </div>
        <input type="hidden" name="empleado" value="{{ empleado }}">
        <input type="hidden" name="typeOfDay" value="ausencia">
        <button type="submit">Guardar fechas</button>
        {% include 'components/flash_message.html' %}
    </form>
    

    <!-- Tabla de fechas aprobadas -->
    <div id="dateTables">
        <h3>Fechas Aprobadas</h3>
        <table>
            <thead>
                <tr>
                    <th>Fecha de inicio</th>
                    <th>Fecha final</th>
                </tr>
            </thead>
            <tbody>
                {% if approved_days %}
                    {% for fecha_inicio, fecha_final in approved_days %}
                    <tr>
                        <td>{{ fecha_inicio }}</td>
                        <td>{{ fecha_final }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>No hay fechas aprobadas</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <!-- Tabla de fechas en espera de autorización -->
        <h3>Fechas en Espera de Autorización</h3>
        <table>
            <thead>
                <tr>
                {% if waiting_days %}
                    <th>Fecha de inicio</th>
                    <th>Fecha final</th>
                    <th>Eliminar</th>
                {% else %}
                    <th>Fecha</th>
                {% endif %}
                </tr>
            </thead>
            <tbody>
                {% if waiting_days %}
                    {% for fecha_inicio, fecha_final in waiting_days %}
                    <tr>
                        <td>{{ fecha_inicio }}</td>
                        <td>{{ fecha_final }}</td>
                        <td class="actionWaitingDate">
                            <!--
                            <form action="/modificacion_fecha_solicitada" method="POST" style="display: inline;">
                                <input type="hidden" name="date" value="{{ dia }}">
                                <button type="submit" class="editarBtn" style="border: none; background: none; cursor: pointer;">
                                    <img src="../static/images/editar.png" alt="Editar" width="20" height="20">
                                </button>
                            </form>
                            -->
                            <form action="/delete_date" method="POST">
                                <input type="hidden" name="date" value="{{ fecha_inicio }}">
                                <input type="hidden" name="typeOfDay" value="ausencia">
                                <button type="submit" class="deleteButton">
                                    <img src="../static/images/eliminar.png" alt="Eliminar">
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>No hay fechas en espera de autorización</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <!-- Tabla de fechas rechazadas -->
        <h3>Fechas rechazadas</h3>
        <table>
            <thead>
                <tr>
                    <th>Fecha de inicio</th>
                    <th>Fecha final</th>
                    <th>Causa</th>
                </tr>
            </thead>
            <tbody>
                {% if rejected_days %}
                    {% for fecha_inicio, fecha_final, causa in rejected_days %}
                    <tr>
                        <td>{{ fecha_inicio }}</td>
                        <td>{{ fecha_final }}</td>
                        <td>{{ causa }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>No hay fechas rechazadas</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/pages/configuracion.html
{% extends 'components/base.html' %}


{% block title %}Configuración{% endblock %}

{% block content %}
    <!-- Formulario para cambiar la contraseña -->
    <div class="containerFormChangePass">
        <form id="changePassForm" action="/save_pass" method="POST">
            <div>
                <input type="hidden" value="{{empleado}}" name="empleado">
                <label for="oldPass">Contraseña anterior:</label>
                <input type="password" id="oldPass" name="oldPass" required>
            </div>
            <div>
                <p>La nueva contraseña debe tener una mayúscula, un número y 8 caracteres mínimo.</p>
                <label for="newPass">Nueva contraseña:</label>
                <input type="password" id="newPass" name="newPass" required>
            </div>
            <div>
                <label for="confirmPass">Confirmar nueva contraseña:</label>
                <input type="password" id="confirmPass" name="confirmPass" required>
            </div>
            <button type="submit">Guardar</button>
        </form>
        {% include 'components/flash_message.html' %}
    </div>
{% endblock %}

templates/pages/descargas.html
{% extends 'components/base.html' %}


{% block title %}Descarga{% endblock %}

{% block content %}
<div class="contenedorDescargas">
  <div class="descargarNominas">
    <a href="/descargar?accion=nomina" class="btn btn-primary">Descargar nómina</a>
    <a href="/descargar?accion=nomina_bajas" class="btn btn-primary">Descargar nómina de bajas</a>
    {% if 'analista de inventario' in roles %}
    <a href="/descargar?accion=inventario_recursos" class="btn btn-primary">Descargar inventario de recursos</a>
  </div>
  {% endif %}
  <div class="formSeleccionarMes">
    <form action="/descargar_nov_mens" method="POST" class="formularioDescarga">
      <label for="mes">Seleccione el mes para descargar novedades:</label>
      <select name="mes" id="mes">
        <option value="1">Enero</option>
        <option value="2">Febrero</option>
        <option value="3">Marzo</option>
        <option value="4">Abril</option>
        <option value="5">Mayo</option>
        <option value="6">Junio</option>
        <option value="7">Julio</option>
        <option value="8">Agosto</option>
        <option value="9">Septiembre</option>
        <option value="10">Octubre</option>
        <option value="11">Noviembre</option>
        <option value="12">Diciembre</option>
      </select>
      <button type="submit" class="btn btn-primary">Descargar novedades mensuales</button>
  </form>
  </div>
</div>

{% endblock %}

templates/pages/documentos.html
{% extends 'components/base.html' %}


{% block title %}Documentos{% endblock %}

{% block content %}
<h2>Listado de Documentos</h2>
<ul>
    {% for documento in lista_documentos %}
    <li><a href="{{ documento.enlace }}" target="_blank">{{ documento.nombre }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

templates/pages/editar_dia.html
{% extends 'components/base.html' %}
{% set roles_editores = ['jefe de area', 'responsable de area', 'supervisor', 'ceo', 'rrhh'] %}

{% block title %}Edición{% endblock %}

{% block content %}
  {% if jerarquia in ['2', '3', '4', '5'] %}
  {% include 'components/dias_aprobados.html'%}
  {% endif %}
  {% if dias_filtrados %}
    {% include 'components/dias_filtrados.html'%}
  {% endif %}
{% endblock %}

templates/pages/estudio.html
{% extends 'components/base.html' %}


{% block title %}Día de estudio{% endblock %}

{% block content %}
    <h2>Módulo de días de estudio</h2>
    <!-- Formulario para guardar día de estudio -->
    <form action="/save_date" method="POST" class="formDia">
        <div class="form-group">
            <label for="requestedDay">Elegir una fecha:</label>
            <input type="date" id="requestedDay" name="requestedDay" required>
            <input type="hidden" value="{{empleado}}">
            <input type="hidden" name="typeOfDay" value="estudio">
        </div>
        <button type="submit">Guardar fecha</button>
    </form>

    {% include 'components/flash_message.html' %}

    {% include 'components/date_tables.html' %}
{% endblock %}

templates/pages/files.html
{% extends 'components/base.html' %}


{% block title %}Archivos{% endblock %}

{% block content %}
<h1>Documentos de la Empresa</h1>
{% if subdir %}
    <p><a href="{{ url_for('files_bp.files', subdir=subdir.rsplit('/', 1)[0]) }}">Volver</a></p>
{% endif %}
<ul class="file-list">
    {% for item in items %}
        {% if item.type == 'folder' %}
            <li class="folder">
                <a href="{{ url_for('files_bp.files', subdir=(subdir ~ '/' ~ item.name) | trim('/') ) }}">
                    <img src="{{ url_for('static', filename='images/archivo-verificado.png') }}" alt="{{ item.name }}" class="icon">
                    {{ item.name }}
                </a>
            </li>
        {% else %}
            <li class="file">
                <a href="{{ url_for('files_bp.download_file', filename=(subdir ~ '/' ~ item.name) | trim('/') ) }}">
                    <img src="{{ url_for('static', filename='images/pdf.png') }}" alt="{{ item.name }}" class="icon">
                    {{ item.name }}
                </a>
            </li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock %}

templates/pages/index.html
{% extends 'components/base.html' %}


{% block enlaces %}
<script src="https://unpkg.com/@phospor-icons/web"></script>
{% endblock %}

{% block title %}Iniciar Sesión{% endblock %}

{% block content %}

<div class="containerLogueo" id="container">
	<div class="form-container sign-in-container">
		<!-- Formulario de inicio de sesión -->
        <form action="/login" method="POST">
            <h1>Iniciar sesión</h1>
            <input type="email" name="email" placeholder="Email" required />
            <input type="password" name="password" placeholder="Contraseña" required />
            <button type="submit">Iniciar sesión</button>
        </form>        
	</div>
	<div class="overlay-container">
		<!-- Información en lado derecho de la Intranet -->
		<div class="overlay">
			<div class="overlay-panel overlay-right">
				<h1>Bienvenido a la Intranet</h1>
				<p>Desde la Intranet podrás realizar gestiones puntuales con RRHH y chequear información personal</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/pages/informacion.html
{% extends 'components/base.html' %}
{% set roles_editores = ['jefe de area', 'responsable de area', 'supervisor', 'ceo', 'rrhh'] %}

{% block title %}Edición{% endblock %}

{% block content %}
    <!-- Si la jerarquia es mayor a 2 o su rol es rrhh mostrará la posibilidad de elegir un empleado -->
    {% if jerarquia in ['2', '3', '4', '5'] or 'rrhh' in roles %}
    <form action="/choose_employee" method="POST" class="formEmployee">
        <div class="form-group">
            <label for="choose_employee">Seleccionar Empleado:</label>
            <select id="choose_employee" name="employee" required>
                <option value="" disabled selected>Elige un empleado</option>
                {% for employee in personal %}
                    <option value="{{ employee }}">{{ employee }}</option>
                {% endfor %}
            </select>
        </div>
        {% if 'rrhh' in roles%}
        <button type="submit">Editar Empleado</button>
        {% else %}
        <button type="submit">Ver Información</button>
        {% endif %}
    </form>
    {% endif %}

    
    {% if info_employee %}
    {% include 'components/info_employee.html' %}
    {% endif %}
    {% if 'rrhh' in roles %}
    {% include 'components/forms/add_employee.html' %}
    {% endif %}
    {% if 'analista de inventario' in roles %}
      {% include 'components/info_recursos.html'%}
    {% endif %}
    {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
{% endblock %}

templates/pages/recursos.html
{% extends 'components/base.html' %}


{% block title %}Recursos{% endblock %}

{% block content %}
    {% if recurso_asignado %}
        <h3>Recursos asignados</h3>
        <table id="recursoTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tipo de equipo</th>
                    <th>Número de serie</th>
                    <th>Marca</th>
                    <th>Modelo</th>
                </tr>
            </thead>
            <tbody>
                {% for recurso in recurso_asignado %}
                <tr>
                    <td>{{ recurso.id }}</td>
                    <td>{{ recurso.tipo_de_equipo }}</td>
                    <td>{{ recurso.nro_serie }}</td>
                    <td>{{ recurso.marca }}</td>
                    <td>{{ recurso.modelo }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No hay recursos asignados.</p>
    {% endif %}
{% endblock %}

templates/pages/rrhh.html
{% extends 'components/base.html' %}


{% block title %}RRHH{% endblock %}

{% block content %}
<p>recu</p>
{% endblock %}

templates/pages/sistemas.html
{% extends 'components/base.html' %}

{% block title %}Reporte a sistemas{% endblock %}

{% block content %}
{% include './components/forms/reportar_a_sistemas.html' %}
  {% if 'sistemas' in roles %}
  {% include './components/ticketera_sistemas.html' %}
  {% endif %}
  {% include './components/tickets_abiertos.html' %}
{% endblock %}

{% block scripts %}
<script src="../../static/js/reporte_a_sistemas.js"></script>
{% endblock %}