src/routes/days.py
from flask import Blueprint, session, render_template
from ..utils.date_db import bring_date_db

#Función que será reutilizada para traer el empleado, roles y personal. También traerá los dias aprobados, rechazados y solicitados de las distintas tablas de la base de datos. Se pasarán los valores que corresponda a través del render_template.
def get_data_and_render_template(template_name, type_of_day):
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']
        approved = bring_date_db(empleado, 'APROBADO', type_of_day)
        rejected = bring_date_db(empleado, 'RECHAZADO', type_of_day)
        required = bring_date_db(empleado, 'SOLICITADO', type_of_day)
        return render_template(template_name, empleado=empleado, roles=roles, personal=personal, rejected_days=rejected, approved_days=approved, waiting_days=required, type_of_day = type_of_day)

# Creación de ruta de estudio
estudio_bp = Blueprint('estudio', __name__)
@estudio_bp.route('/estudio')
def estudio():
    return get_data_and_render_template('pages/estudio.html', 'estudio')

# Creación de ruta de home
home_bp = Blueprint('home', __name__)
@home_bp.route('/home')
def home():
    return get_data_and_render_template('pages/home.html', 'home')

# Creación de ruta de ausencia
ausencia_bp = Blueprint('ausencia', __name__)
@ausencia_bp.route('/ausencia')
def ausencia():
    return get_data_and_render_template('pages/ausencia.html', 'ausencia')

vacaciones_bp = Blueprint('vacaciones', __name__)
@vacaciones_bp.route('/vacaciones')
def vacaciones():
    return get_data_and_render_template('pages/vacaciones.html', 'vacaciones')

src/routes/files.py
from flask import Blueprint, send_from_directory, render_template, url_for
import os

# Crea el blueprint
files_bp = Blueprint('files_bp', __name__, template_folder='templates')

# Configura la ruta donde se almacenan los archivos
current_dir = os.path.dirname(os.path.abspath(__file__))
FILE_DIRECTORY = os.path.join(current_dir, '../../static/files')

def list_items(directory):
    items = []
    for name in os.listdir(directory):
        path = os.path.join(directory, name)
        if os.path.isdir(path):
            items.append({'type': 'folder', 'name': name})
        else:
            items.append({'type': 'file', 'name': name})
    return items

@files_bp.route('/')
@files_bp.route('/<path:subdir>')
def files(subdir=''):
    directory = os.path.join(FILE_DIRECTORY, subdir)
    items = list_items(directory)
    return render_template('pages/files.html', items=items, subdir=subdir)

@files_bp.route('/download/<path:filename>')
def download_file(filename):
    return send_from_directory(FILE_DIRECTORY, filename)

src/routes/inicio.py
# Importaciones
from flask import Blueprint, render_template, session
from ..utils.tablas_inicio import obtener_cumpleanios, obtener_claves
from ..utils.date_db import bring_approved, obtener_feriados
import json

# Crea un objeto Blueprint
inicio_bp = Blueprint('inicio', __name__)

# Define la ruta para la página de inicio de sesión
@inicio_bp.route('/inicio')
def inicio():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        area = session['area']
        jerarquia = session['jerarquia']
        personal = session['personal']
        print(roles)
        cumpleanios = obtener_cumpleanios()
        claves = obtener_claves(area)
        fechas_aprobadas_totales = {}
        # Verificar si personal es una lista
        if isinstance(personal, list):
            for persona in personal:
                fechas_aprobadas = bring_approved(persona)
                fechas_aprobadas_totales[persona] = fechas_aprobadas
        else:
            fechas_aprobadas = bring_approved(personal)
            fechas_aprobadas_totales[personal] = fechas_aprobadas

        fechas_aprobadas_json = json.dumps(fechas_aprobadas_totales)
        #print(fechas_aprobadas_json)
        feriados = obtener_feriados()
        print(feriados)

        return render_template('pages/inicio.html', empleado=empleado, roles=roles, cumpleanios=cumpleanios, area=area, claves=claves, fechas_aprobadas=fechas_aprobadas_json, jerarquia=jerarquia)

src/routes/rrhh.py
# Importaciones
from flask import Blueprint, session, render_template
# Se crea la ruta resources
rrhh_bp = Blueprint('rrhh', __name__)
@rrhh_bp.route('/rrhh')
def rrhh():
    if 'user' in session:
        empleado = session['empleado']
        roles = session['roles']
        personal = session['personal']
        
        return render_template('pages/rrhh.html', empleado = empleado, roles = roles, personal = personal)

templates/components/aprobacion.html
{% if dias_por_aprobar %}
<div class="tablaDropdown">
    <div class="dropdownHeader" onclick="toggleDropdown()">Fechas por aprobar</div>
    <div class="dropdownContent">
        <form id="aprobarForm" action="/aprobar_solicitud" method="POST">
            <div class="table-container">
                <table class="aprobarSolicitudes">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="selectAll" onclick="toggleAll(this)"></th>
                            <th>Empleado</th>
                            <th>Fecha de Inicio</th>
                            <th>Fecha Final</th>
                            <th>Concepto</th>
                            <th>Fecha de Solicitud</th>
                            <th>Estado</th>
                            <th>Causa</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lista_dias in dias_por_aprobar %}
                            {% for solicitud in lista_dias %}
                            <tr>
                                <td><input type="checkbox" name="solicitudes" value="{{ solicitud.empleado }}|{{ solicitud.fecha_inicio }}|{{ solicitud.concepto }}"></td>
                                <td>{{ solicitud.empleado }}</td>
                                <td>{{ solicitud.fecha_inicio }}</td>
                                <td>{{ solicitud.fecha_fin }}</td>
                                <td>{{ solicitud.concepto }}</td>
                                <td>{{ solicitud.fecha_solicitud }}</td>
                                <td>{{ solicitud.estado }}</td>
                                <td>{{ solicitud.causa }}</td>
                                <td>
                                    <button type="button" class="rechazarBtn" onclick="rechazarSolicitud('{{ solicitud.empleado }}', '{{ solicitud.fecha_inicio }}', '{{ solicitud.concepto }}')">Rechazar</button>
                                </td>
                            </tr>
                            {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <button type="submit" class="aprobarBtn">Aprobar Seleccionados</button>
        </form>
    </div>
</div>
{% endif %}
<script>
    function toggleAll(selectAllCheckbox) {
        var checkboxes = document.querySelectorAll('input[name="solicitudes"]');
        checkboxes.forEach(checkbox => checkbox.checked = selectAllCheckbox.checked);
    }

    document.getElementById('aprobarForm').addEventListener('submit', function(event) {
        var selected = document.querySelectorAll('input[name="solicitudes"]:checked').length;
        if (selected === 0) {
            alert("Por favor, selecciona al menos una solicitud para aprobar.");
            event.preventDefault();
        } else if (!confirm("¿Estás seguro de que deseas aprobar las solicitudes seleccionadas?")) {
            event.preventDefault();
        }
    });

    function rechazarSolicitud(empleado, fecha, concepto) {
        if (confirm("¿Estás seguro de que deseas rechazar esta solicitud?")) {
            const form = document.createElement('form');
            form.method = 'POST';
            form.action = '/eliminar_solicitud';

            const empleadoInput = document.createElement('input');
            empleadoInput.type = 'hidden';
            empleadoInput.name = 'empleado';
            empleadoInput.value = empleado;
            form.appendChild(empleadoInput);

            const fechaInput = document.createElement('input');
            fechaInput.type = 'hidden';
            fechaInput.name = 'fecha';
            fechaInput.value = fecha;
            form.appendChild(fechaInput);

            const conceptoInput = document.createElement('input');
            conceptoInput.type = 'hidden';
            conceptoInput.name = 'concepto';
            conceptoInput.value = concepto;
            form.appendChild(conceptoInput);

            document.body.appendChild(form);
            form.submit();
        }
    }
</script>
<style>
.table-container {
    max-height: 400px; /* Ajusta esta altura según sea necesario */
    overflow-y: auto;
    border: 1px solid #ddd;
}

.aprobarSolicitudes {
    width: 100%;
    border-collapse: collapse;
}

.aprobarSolicitudes thead th {
    position: sticky;
    top: 0;
    z-index: 1;
}

.aprobarSolicitudes th, .aprobarSolicitudes td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
}

.aprobarSolicitudes th {
    font-weight: bold;
}
</style>

templates/components/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <script src="https://unpkg.com/@phosphor-icons/web" crossorigin="anonymous"></script>
    {% block enlaces %}{% endblock %}
    <!-- Nombre de la pestaña -->
    <title>{% block title %}Mi Sitio Web{% endblock %}</title>
</head>
<body>
    <div class="container">
        <!-- Menú lateral -->
        <div class="menu-lateral">
            {% block menu_lateral %}
                {% include 'components/menu_lateral.html' %}
            {% endblock %}
        </div>
        
        <!-- Contenido de la página -->
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    {% block scripts %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="../static/js/app.js"></script>
</body>
</html>

templates/components/calendario.html
    <div class="containerCalendar">
      <div class="left">
        <div class="calendar">
          <div class="month">
            <i class="ph-bold ph-arrow-left prev"></i>
            <div class="date"></div>
            <i class="ph-bold ph-arrow-right next"></i>
          </div>
          <div class="weekdays">
            <div>Dom</div>
            <div>Lun</div>
            <div>Mar</div>
            <div>Mier</div>
            <div>Jue</div>
            <div>Vie</div>
            <div>Sab</div>
          </div>
          <div class="days"></div>
          <div class="goto-today">
            <div class="goto">
              <input type="text" placeholder="mm/yyyy" class="date-input" />
              <button class="goto-btn">Ir</button>
            </div>
            <button class="today-btn">Hoy</button>
          </div>
        </div>
      </div>
      <div class="right">
        <div class="today-date">
          <div class="event-day">wed</div>
          <div class="event-date">12th december 2022</div>
        </div>
        <div class="events"></div>
        <div class="add-event-wrapper">
          <div class="add-event-header">
            <div class="title">Agregar evento</div>
            <i class="ph-bold ph-x close"></i>
          </div>
          <div class="add-event-body">
            <div class="add-event-input">
              <input type="text" placeholder="Event Name" class="event-name" />
            </div>
            <div class="add-event-input">
              <input
                type="text"
                placeholder="Event Time From"
                class="event-time-from"
              />
            </div>
            <div class="add-event-input">
              <input
                type="text"
                placeholder="Event Time To"
                class="event-time-to"
              />
            </div>
          </div>
          <div class="add-event-footer">
            <button class="add-event-btn">Agregar evento</button>
          </div>
        </div>
      </div>
      <!--
      <button class="add-event">
        <i class="ph-bold ph-plus"></i>
      </button>
      -->
    </div>

    <script>
      let fechasAprobadas = {{ fechas_aprobadas | safe }};
      let empleado = "{{ empleado }}";
      console.log(empleado)
      console.log(fechasAprobadas)
  </script>
  

templates/components/claves.html
{% if claves %}
<div class="contenedorClaves">
    <h3>Claves</h3>
        <!-- Tabla de claves de los distintos mails que se usa por sector -->
        <table class="tablaClaves">
            <thead>
                <tr>
                    <th>Sistema</th>
                    <th>Mail</th>
                    <th>Clave</th>
                </tr>
            </thead>
            <tbody>
                {% for clave in claves %}
                    <tr>
                        <td>{{ clave['plataforma'] }}</td>
                        <td>{{ clave['mail'] }}</td>
                        <td>{{ clave['clave'] }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

templates/components/date_tables.html
<div id="dateTables">
    <!-- Fechas aprobadas -->
    <h3>Fechas Aprobadas</h3>
    <table>
        <thead>
            <tr>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
            {% if approved_days %}
                {% for dia in approved_days %}
                <tr>
                    <td>{{ dia }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>No hay fechas aprobadas</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- Fechas en espera de autorización -->
    <h3>Fechas en Espera de Autorización</h3>
    <table>
        <thead>
            <tr>
            {% if waiting_days %}
                <th>Fecha</th>
                <th>Eliminar</th>
            {% else %}
                <th>Fecha</th>
            {% endif %}
            </tr>
        </thead>
        <tbody>
            {% if waiting_days %}
                {% for dia in waiting_days %}
                <tr>
                    <td>{{ dia }}</td>
                    <td class="actionWaitingDate">
                        <!--
                        <form action="/modificacion_fecha_solicitada" method="POST" style="display: inline;">
                            <input type="hidden" name="date" value="{{ dia }}">
                            <button type="submit" class="editarBtn" style="border: none; background: none; cursor: pointer;">
                                <img src="../static/images/editar.png" alt="Editar" width="20" height="20">
                            </button>
                        </form>
                        -->
                        <form action="/delete_date" method="POST">
                            <input type="hidden" name="date" value="{{ dia }}">
                            <input type="hidden" name="typeOfDay" value="{{ type_of_day }}">
                            <button type="submit" class="deleteButton">
                                <img src="../../static/images/eliminar.png" alt="Eliminar">
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>No hay fechas en espera de autorización</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- Fechas rechazadas -->
    <h3>Fechas rechazadas</h3>
    <table>
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Causa</th>
            </tr>
        </thead>
        <tbody>
            {% if rejected_days %}
                {% for dia, causa in rejected_days %}
                <tr>
                    <td>{{ dia }}</td>
                    <td>{{ causa }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>No hay fechas rechazadas</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

templates/components/dias_aprobados.html
{% if fechas_aprobadas %}
    <form action="/filtrar_dias" method="POST" class="filtrarDias" onsubmit="return validarFechas()">
        <label for="empleado">Empleado:</label>
        <select name="empleado" id="empleado">
            <option value="todos">Todos los empleados</option>
            {% for empleado in personal %}
                <option value="{{ empleado }}">{{ empleado }}</option>
            {% endfor %}
        </select>

        <label for="concepto">Concepto:</label>
        <select name="concepto" id="concepto">
            <option value="dia_ausencia">Ausencia</option>
            <option value="dia_vacaciones">Vacaciones</option>
            <option value="dia_home">Home Office</option>
            <option value="dia_estudio">Día de estudio</option>
        </select>

        <label for="fecha">Fecha:</label>
        <input type="date" name="fecha" id="fecha">

        <label for="fecha_fin">Fecha Final:</label>
        <input type="date" name="fecha_fin" id="fecha_fin">

        <button type="submit">Filtrar</button>
    </form>
{% endif %}

templates/components/dias_filtrados.html
<table class="diasFiltrados">
    <thead>
      <tr>
        <th>Empleado</th>
        <th>Fecha de Inicio</th>
        <th>Fecha Final</th>
        <th>Fecha de Solicitud</th>
        <th>Estado</th>
        <th>Causa</th>
        <th>Acción</th>
      </tr>
    </thead>
    <tbody>
        {% for dia in dias_filtrados %}
        <form action="/editar_dia" method="POST">
            <tr>
                <td><input type="text" name="empleado" value="{{ dia.empleado }}" readonly></td>
                <td><input type="date" name="fecha_inicio" value="{{ dia.fecha_inicio }}"></td>
                <td><input type="date" name="fecha_final" value="{{ dia.fecha_final }}"></td>
                <td><input type="text" name="fecha_solicitud" value="{{ dia.fecha_solicitud }}" readonly></td>
                <td><input type="text" name="estado" value="{{ dia.estado }}"></td>
                <td><input type="text" name="causa" value="{{ dia.causa }}"></td>
                <input type="hidden" name="concepto" value="{{ dia.concepto }}">
                <input type="hidden" name="superior" value="{{ empleado }}">
                <td>
                    <button type="submit">Editar</button>
                </td>
            </tr>
            <input type="hidden" name="empleado" value="{{ dia.empleado }}">
            <input type="hidden" name="fecha_inicio" value="{{ dia.fecha_inicio }}">
        </form>
        {% endfor %}
    </tbody>
    
  </table>
  

templates/components/flash_message.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
        <p class="flash-message flash-{{ category }}" style="margin-top: 5px;">{{ message }}</p>
    {% endfor %}
{% endif %}
{% endwith %}

templates/components/info_employee.html
{% if jerarquia in ['2'] %}
<p>{{info_employee['empleado']}}</p>
<p>{{info_employee['cuil']}}</p>
<p>{{info_employee['fecha_ingreso']}}</p>
<p>{{info_employee['legajo']}}</p>
<p>{{info_employee['mail']}}</p>
<p>{{info_employee['fecha_nacimiento']}}</p>
<p>{{info_employee['categoria']}}</p>
<p>{{info_employee['convenio']}}</p>
<!--
<p>{{info_employee['forma']}}</p>
<p>{{info_employee['turno']}}</p>
<p>{{info_employee['area']}}</p>
<p>{{info_employee['jerarquia']}}</p>
-->
{% endif %}

{% if jerarquia in ['3'] %}
    {% include 'components/forms/view_employee_info.html' %}
    {% include 'components/forms/save_home_office.html' %}
{% endif %}

{% if jerarquia in ['4', '5'] %}
    {% include 'components/forms/view_employee_info.html' %}
{% endif %}

{% if 'rrhh' in roles %}
    {% include 'components/forms/edit_employee_info.html' %}
{% endif %}

templates/components/links.html
<a href=" https://apps-wmms.mitrol.cloud/webpad/login">Mitrol Web Pad</a>
<a href="https://apps-wmms.mitrol.cloud/supervisor ">Supervisor Web</a>
<a href="https://apps-wmms.mitrol.cloud/aw">Administrador</a>
<a href="https://apps-wmms.mitrol.cloud/reportes ">Reportería</a>

templates/components/menu_lateral.html
{% set roles_superiores = ['jefe de area', 'responsable de area', 'supervisor', 'ceo', 'sistemas', 'rrhh'] %}
<div class="containerSidebar">
    <div class="sidebar active">
        <!--
        <div class="menu-btn">
            <i class="ph-bold ph-caret-left"></i>
        </div>
        -->
        <div class="headSidebar">
            <div class="imagenUsuarioSidebar">
                <img src="{{ url_for('static', filename='images/user.png') }}" alt="Imagen del usuario">
            </div>
            <div class="detallesUsuario">
                <p class="title">Puesto</p>
                <p class="name"></p>
            </div>
        </div>
        <div class="nav">
            <div class="menu">
                <p class="title">{{ empleado }}</p>
                <ul>
                    <li class="active">
                        <a href="{{ url_for('inicio.inicio') }}">
                            <i class="icon ph-bold ph-house-simple"></i>
                            <span class="text">Inicio</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="ph-bold ph-calendar-blank"></i>
                            <span class="text">Dias</span>
                            <i class="arrow ph-bold ph-caret-down"></i>
                        </a>
                        <ul class="subMenu">
                            <li>
                                <a href="{{ url_for('estudio.estudio') }}">
                                    <span class="text">Dias de estudio</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('ausencia.ausencia') }}">
                                    <span class="text">Días de ausencia</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('home.home') }}">
                                    <span class="text">Días de home</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('vacaciones.vacaciones') }}">
                                    <span class="text">Vacaciones</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!--
                    <li class="">
                        <a href="{{ url_for('files_bp.files') }}">
                            <i class="ph-bold ph-file-text"></i>
                            <span class="text">Documentos</span>
                        </a>
                    </li>
                    
                    <li>
                        <a href="#">
                            <i class="ph-bold ph-chart-bar"></i>
                            <span class="text">Capacitaciones</span>
                        </a>
                    </li>
                    -->
                    <li>
                        <a href="#">
                            <i class="ph-bold ph-user"></i>
                            <span class="text">Personal</span>
                            <i class="arrow ph-bold ph-caret-down"></i>
                        </a>
                        <ul class="subMenu">
                            <!-- MAS ADELANTE
                            <li>
                                <a href="#">
                                    <span class="text">Recibos</span>
                                </a>
                            </li>
                            -->
                            <li>
                                <a href="{{ url_for('recursos.recursos') }}">
                                    <span class="text">Recursos</span>
                                </a>
                            </li>
                            {% if 'jefe de area' in roles or 'responsable de area' in roles or 'supervisor' in roles or 'ceo' in roles or 'sistemas' in roles or 'rrhh' in roles %}                       
                            <li>
                                <a href="{{ url_for('descargas.descargas') }}">
                                    <span class="text">Descargas</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('informacion.informacion') }}">
                                    <span class="text">Informacion del empleado</span>
                                </a>
                            </li>         
                            <li>
                                <a href="{{ url_for('aprobacion.aprobacion') }}">
                                    <span class="text">Aprobacion de días</span>
                                </a>
                            </li> 
                            <li>
                                <a href="{{ url_for('editarDia.editarDia') }}">
                                    <span class="text">Editar días</span>
                                </a>
                            </li>          
                            {% endif %}
                            {% if 'rrhh' in roles%}
                            <li>
                                <a href="{{ url_for('rrhh.rrhh') }}">
                                    <span class="text">RRHH</span>
                                </a>
                            </li>
                            {% endif %}

                        </ul>
                    </li>
                </ul>
            </div>
            <div class="menu">
                <p class="title">Reportar</p>
                <ul>
                    <li>
                        <a href="{{ url_for('sistemas.sistemas') }}">
                            <i class="ph-bold ph-windows-logo"></i>
                            <span class="text">Sistemas</span>
                        </a>
                    </li>
                    <!--
                    {% for rol in roles %}
                        {% if rol in roles_superiores and rol != 'ceo' %}
                        <li>
                            <a href="#">
                                <i class="ph-bold ph-person-simple"></i>
                                <span class="text">Superior inmediato</span>
                            </a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    -->
                </ul>
            </div>
            <div class="menu">
                <p class="title">Account</p>
                <ul>
                    <li>
                        <a href="{{ url_for( 'configuracion.configuracion') }}">
                            <i class="ph-bold ph-gear"></i>
                            <span class="text">Configuración</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for( 'logout.logout' ) }}">
                            <i class="ph-bold ph-sign-out"></i>
                            <span class="text">Cerrar sesión</span>
                        </a>                        
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>

templates/components/ticketera_sistemas.html
{% if reportes_a_sistemas %}
{% include 'components/tables/ticketera_table.html' %}
{% endif %}

templates/components/tickets_abiertos.html
{% if obtener_tickets %}
{% include 'components/tables/tickets_abiertos_table.html' %}
{% endif %}